version: 2.1

commands:
    run_server:
        steps:
          - run:
              name: "Start da server"
              command: npm run start &
    zap_scan:
        steps:
          - run:
              name: "fire away"
              command: docker run --user root --network=host -t owasp/zap2docker-stable zap-full-scan.py -t http://localhost:3000 -J report_json.json -w report_md.md -r report_html.html

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: node:lts
        auth:
          username: stknight2021
          password: $DOCKER_HUB_ACCESS_TOKEN  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: "Install npm deps"
          command: npm install --ignore-scripts
      - run_server
  test:
    docker:
      - image: node:lts
        auth:
          username: stknight2021
          password: $DOCKER_HUB_ACCESS_TOKEN  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
