version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/python:3.9
        auth:
          username: stknight2021
          password: $DOCKER_HUB_ACCESS_TOKEN  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/python:3.9
        auth:
          username: stknight2021
          password: $DOCKER_HUB_ACCESS_TOKEN  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
