version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: node:lts
        auth:
          username: stknight2021
          password: $DOCKER_HUB_ACCESS_TOKEN  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: "Install npm deps"
          command: npm install --ignore-scripts
  test:
    docker:
      - image: node:lts
        auth:
          username: stknight2021
          password: $DOCKER_HUB_ACCESS_TOKEN  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
